/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                    '#3c5661',
        'on-primary':                 '#ffffff',
        'primary-container':          '#546e7a',
        'on-primary-container':       '#d4f0fe',
        'primary-fixed':              '#cbe7f5',
        'primary-fixed-dim':          '#afcbd8',
        'on-primary-fixed':           '#021f29',
        'on-primary-fixed-variant':   '#304a55',
        'inverse-primary':            '#afcbd8',

        'secondary':                  '#1b6d24',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#a0f399',
        'on-secondary-container':     '#217128',
        'secondary-fixed':            '#a3f69c',
        'secondary-fixed-dim':        '#88d982',
        'on-secondary-fixed':         '#002204',
        'on-secondary-fixed-variant': '#005312',

        'tertiary':                   '#a60b15',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#ca2b2a',
        'on-tertiary-container':      '#ffe6e3',
        'tertiary-fixed':             '#ffdad6',
        'tertiary-fixed-dim':         '#ffb4ac',
        'on-tertiary-fixed':          '#410003',
        'on-tertiary-fixed-variant':  '#93000e',

        'background':                 '#f3faff',
        'on-background':              '#021f29',

        'surface':                    '#f3faff',
        'on-surface':                 '#021f29',
        'surface-variant':            '#cbe7f5',
        'on-surface-variant':         '#42484b',
        'surface-dim':                '#c3deec',
        'surface-bright':             '#f3faff',
        'surface-tint':               '#48626e',
        'inverse-surface':            '#19343e',
        'inverse-on-surface':         '#dff4ff',

        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#e6f6ff',
        'surface-container':          '#d8f2ff',
        'surface-container-high':     '#d1ecfa',
        'surface-container-highest':  '#cbe7f5',

        'outline':                    '#72787b',
        'outline-variant':            '#c2c7cb',

        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'Sarabun', 'sans-serif'],
        body:     ['Inter', 'Sarabun', 'sans-serif'],
        label:    ['Inter', 'Sarabun', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.25rem',
        md:      '0.75rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      boxShadow: {
        editorial: '0 12px 32px rgba(2, 31, 41, 0.06)',
        float:     '0 12px 32px rgba(60, 86, 97, 0.25)',
      },
    },
  },
  plugins: [],
}
